#!/bin/bash

docker run \
-d \
--name santa-app \
--net santa \
-e MONGO_HOST=${MONGO_HOST} \
-e MONGO_PORT=${MONGO_PORT} \
-e MONGO_USER=${MONGO_USER} \
-e MONGO_PASS=${MONGO_PASS} \
-e MONGO_DB=${MONGO_DB} \
-e FACEBOOK_APP_ID=${FACEBOOK_APP_ID} \
-p 3000:3000 \
secret-santa
